# This is a basic workflow to help you get started with Actions

name: Latest YouTube Videos workflow

# Controls when the workflow will run
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * ?' # Runs every hour, on the hour

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-readme-with-videos"
  update-readme-with-videos:
    name: Update this repo's README with latest videos from YouTube
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          commit_message: "Updated README with latest YouTube video"
          feed_list: "https://youtube.com/feeds/videos.xml?channel_id=UCisFyyuGQyco-ZCZHlOJoVw"
